In [1]:
import torch
from torch.utils.data import Dataset
torch.manual_seed(1)

In [11]:
class toy_set(Dataset):

    def __init__(self, length = 100, transform = None):
        self.len = length
        self.x = 2 * torch.ones(length,2)
        self.y = 2 * torch.ones(length,1)
        self.transform = transform

    def __getitem__(self,index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
        
    def __len__(self):
        return self.len
        

In [12]:
our_dataset = toy_set()
print("Object ",our_dataset)
print("Zero index", our_dataset[0])
print(len(our_dataset))

Object  <__main__.toy_set object at 0x1657f62d0>
Zero index (tensor([2., 2.]), tensor([2.]))
100


In [13]:
for i in range(3):
    x,y = our_dataset[i]
    print("Index: ",i," and X is ",x, "and Y is ",y)

Index:  0  and X is  tensor([2., 2.]) and Y is  tensor([2.])
Index:  1  and X is  tensor([2., 2.]) and Y is  tensor([2.])
Index:  2  and X is  tensor([2., 2.]) and Y is  tensor([2.])


In [ ]:
for x,y in our_dataset:
    print("x: ",x, "Y: ", y)

In [18]:
new_dataset = toy_set(length=50)
print(len(new_dataset))

for x,y in new_dataset:
    print("x: ",x, "Y: ", y)

50
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tensor([2., 2.]) Y:  tensor([2.])
x:  tenso

In [20]:
class add_mult(object):
    def __init__(self, addx =1, muly=2):
        self.addx = addx
        self.muly = muly
    
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y =  y * self.muly

        sample = x,y
        return sample
        

In [21]:
a_m = add_mult()
data_set = toy_set()

In [22]:
for i in range(10):
    x,y  = data_set[i]
    print('Index: ', i, 'Original x: ', x, 'Original y: ', y)
    x_,y_ = a_m(data_set[i])
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)

Index:  0 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  0 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  1 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  1 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  2 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  2 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  3 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  3 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  4 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  4 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  5 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  5 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  6 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  6 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  7 Original x:  tensor([2.,

In [23]:
cust_data_set = toy_set(transform=a_m)



In [24]:
for i in range(10):
    x,y = data_set[i]
    print('Index: ', i, 'Original x: ', x, 'Original y: ', y)
    x_, y_ = cust_data_set[i]
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)

Index:  0 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  0 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  1 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  1 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  2 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  2 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  3 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  3 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  4 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  4 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  5 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  5 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  6 Original x:  tensor([2., 2.]) Original y:  tensor([2.])
Index:  6 Transformed x_: tensor([3., 3.]) Transformed y_: tensor([4.])
Index:  7 Original x:  tensor([2.,

In [26]:
#Create a new transform class my_add_mult
class my_add_mult(object):
    
    def __init__(self, addx = 2,muly = 3):
        self.addx = addx
        self.muly = muly

    def __call__(self, sample):
        x = sample [0]
        y = sample [1]
        
        x = x + self.addx + self.muly
        y = y / self.muly + self.addx

        sample = x,y

        return sample

myam = my_add_mult()
test_dataset = toy_set(transform=myam)

for i in range(3):
    x,y = test_dataset[i]
    print(x,y)

tensor([7., 7.]) tensor([2.6667])
tensor([7., 7.]) tensor([2.6667])
tensor([7., 7.]) tensor([2.6667])


In [27]:
from torchvision import transforms