In [1]:
import torch
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [7]:
list = [[1,2,3],[3,4,5],[5,6,7]]
a = torch.Tensor(list)

print("List "+ str(list))
print("")
print("Tensor "+ str(a))


List [[1, 2, 3], [3, 4, 5], [5, 6, 7]]

Tensor tensor([[1., 2., 3.],
        [3., 4., 5.],
        [5., 6., 7.]])


In [ ]:
print(a.ndimension())
print("Shape is "+str(a.size()))
print("Number of elemets is "+ str(a.numel()))

2
Shape is torch.Size([3, 3])
Number of elemets is 9


In [20]:
x = torch.Tensor([[1,2],[2,3]])
y = torch.Tensor([[4,5],[5,6]])

z = x*y
print(x)
print(y)
print("Multiple is "+str(z))

tensor([[1., 2.],
        [2., 3.]])
tensor([[4., 5.],
        [5., 6.]])
Multiple is tensor([[ 4., 10.],
        [10., 18.]])


In [22]:
a = torch.Tensor([[1,2],[2,3],[4,5]])
b = torch.Tensor([[1,2,3],[2,3,4]])

c = torch.mm(a,b)

print(c)

tensor([[ 5.,  8., 11.],
        [ 8., 13., 18.],
        [14., 23., 32.]])
