In [2]:
import torch
from torch.nn import Linear

In [13]:
torch.manual_seed(10)

In [14]:
model = Linear(in_features=1,out_features=1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.0838]], requires_grad=True), Parameter containing:
tensor([-0.0343], requires_grad=True)]


In [ ]:
# x = torch.tensor([0.0])
# yhat = model(x)
# print(yhat)

tensor([-0.0343], grad_fn=<ViewBackward0>)


In [18]:
x = torch.tensor([[1.0],[2.0]])
yhat = model(x)
print(yhat)

tensor([[-0.1181],
        [-0.2019]], grad_fn=<AddmmBackward0>)
