In [4]:
import torch
import torch.nn as nn

In [6]:
class LR(nn.Module):
    def __init__(self,in_size,output_size):
        super (LR,self).__init__()
        self.linear = nn.Linear(in_size,output_size)

    def forward (self,x):
        out = self.linear(x)
        return out


In [11]:
model = LR(1,1)
model.state_dict()['linear.weight'].data[0] = torch.tensor([0.5152])
model.state_dict()['linear.bias'].data[0] = torch.tensor([-0.4414])

print(list(model.parameters()))

x = torch.tensor([1.0])
yhat = model(x)

print(yhat)

[Parameter containing:
tensor([[0.5152]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
tensor([0.0738], grad_fn=<ViewBackward0>)
